on:
  push:
    branches:
      - workflow_testing_lukas
  workflow_dispatch:
name: Heroku Deployment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build frontend; do dir magic
        run: |
          cd frontend/ && npm install && CI=false npm run build
          cd ..
          mv ./frontend/build ./
          rm -r frontend
          mv ./server/* ./
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'ark-automate'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - run: heroku git:remote -a ark-automate
      - run: git config user.email "heroku.deployer@ark-automate.com" && git config user.name "Heroku Deployer" && git add . && git commit -m "heroku deployment commit"
      - run: git push heroku HEAD:master --force
