name: Publish Documentation to GitHub pages

on:
  push:
    branches:
      - 281_documentation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: navigate to frontend and build
        run: cd ./frontend/ && npm install --save-dev better-docs jsdoc && npm run docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentationWebsite
